language: java
jdk:
  - openjdk17

branches:
  only:
    - master

# Travis CI 서버의 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

# CI 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - pjaemin@gmail.com