language: java
jdk:
  - openjdk17

branches:
  only:
    - master

# Travis CI 서버의 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r webservice-demo *
  - mkdir -p deploy
  - mv webservice-demo.zip deploy/webservice-demo.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-builder
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-builder
    key: webservice-demo.zip
    bundle_type: zip
    application: freelec-springboot2-webservice
    deployment_group: freelec-springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - pjaemin@gmail.com