version: 0.2

phases:
  build:
    commands:
      - echo "Entered build phase"
      - chmod +x ./gradlew
      - ./gradlew build

artifacts:
  files:
    - appspec.yml
    - scripts/*.sh
    - build/libs/*.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'